version: '3'
services:
  angular-app:
    image: angular-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    restart: always

networks:
  bridge-network:
    driver: bridge