version: '3'
services:
  angular-app:
    image: angular-app:latest
    container_name: admin-panel
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    restart: always
    networks:
      - ondergrup-network

networks:
  ondergrup-network:
    external: true